[jump]
jump-host ansible_host=34.118.111.49 ansible_port=9922

[node01]
node-01 ansible_host=10.0.1.12 ansible_port=9922

[node02]
node-02 ansible_host=10.0.1.13 ansible_port=9922

[node03]
node-03 ansible_host=10.0.1.11 ansible_port=9922

[internal:children]
node01
node02
node03

[all:vars]
ansible_user=bkr_ops
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
